config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'

  resources :cocktails, only: %i[ show new create destroy] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, presence: true, uniqueness: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @ingredients = Ingredient.new
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="homepage-background d-flex flex-column align-items-center justify-content-center">
  <div class="d-flex flex-column fade">
    <h1 class="page-title">Mr Cocktail</h1>
  </div>

  <div class="container text-center">
    <a href="#list-of-cocktails" class="btn-homepage">View Menu</a>
    <%= link_to 'Make My Own', new_cocktail_path, class: 'btn-homepage' %>
  </div>

 <!--  <div class="container text-center">
    <form action="">
      <input type="text" placeholder="Search...">
      <input type="submit">
    </form>
  </div> -->

</div>

<div class="index-background">
  <div class="container">


  <div class="row" id="list-of-cocktails">
  <!-- Sort class instances alphabetically by name -->
  <% @cocktails = @cocktails.sort_by(&:name) %>

    <!-- Display cocktail instances -->
    <% @cocktails.each do |cocktail| %>
    <div class="col-md-4 d-flex align-items-stretch">
      <div class="card my-4 shadow-sm" style="width: 100%;" data-aos="zoom-in-up">
        <div class="card-body">
          <h5 class="card-title"><%= cocktail.name.split.map(&:capitalize).join(' ') %></h5>
          <%= link_to 'View Cocktail', cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <!-- End of Container -->
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Create your own</h1>
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :review, label: "Method" %>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= f.submit "Add Cocktail", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container mt-4">
  <h1 class="text-center"><%= @cocktail.name.split.map(&:capitalize).join(' ') %></h1>

  <% @cocktail.doses.each do |dose| %>
  <div class="d-flex">
  <p><%= link_to dose_path(dose), method: :delete, data: { confirm: "Remove ingredient?" }, class: 'text-muted' do %>
    <i class="fas fa-trash text-danger mr-3"></i>
  <% end %>
  <p class="font-weight-bold"><span><%= dose.description %></span> <span><%= dose.ingredient.name %></span></p>
  </div>

  <% end %></p>

    <%= link_to 'Add Ingredient', new_cocktail_dose_path(@cocktail), class: 'btn btn-success' %>

    <%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
  </div>

app/views/doses/new.html.erb
<div class="container">
  <h1 class="text-center"><%= @cocktail.name.split.map(&:capitalize).join(' ') %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description, label: "Measurement" %>
  <%= f.association :ingredient %>
  <%= f.submit "Add Dose", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>🍸 Mr Cocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% unless action_name == "index" %>
    <%= render 'components/nav' %>
  <% end %>
  <%= yield %>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
</body>
</html>